### ISSUE TITLE
Shapeways error

### ISSUE THREAD

**Issue by giammin** [egladman/hhkb-usb-cover#5]
Hi,

I uploaded yourmodel on shapeways and had this error. 

> Unfortunately, the model you recently uploaded usb_cover did not pass our initial printability checks, so it's not yet ready for 3D printing. Printability Error:
> STL positions outside sane range. Likely STL ASCII file with no solid keyword

I dont know anything about 3d modelling and wonder if you could help.

Another thing: measures are mm or inch?

**Comment by egladman** [comment]
Hey @giammin,

It's been so long since I've worked on this, but I'll do my best to help. I'm currently traveling so I don't have access to a computer, otherwise I'd play around with the compiled STL. 

Years prior I had Shapeways print this model during early testing. They might've changed print requirements since I last used them. Or maybe the print material is incompatible due to tolerances. 

Measurements are in millimeters.

**Comment by giammin** [comment]
thank you very much!

**Comment by egladman** [comment]
@giammin did you ever figure it out? If not I'd suggest trying the STL from d1ba2702c2e38df9d22610d7d844e089ca2c2a09 before i reoriented the model.

**Comment by giammin** [comment]
Thanks! That version works with shapeways.

The problem is that the cheapest is 9$ each without shipping 

Did not expect it was so expensive.
